### ISSUE TITLE
Introducing of all the distillations

### ISSUE THREAD

**Issue by rose-jinyang** [VaticanCameos99/knowledge-distillation-for-unet#1]
Hello
How are you?
Thanks for contributing to this project.
I think that u have introduced only Pixel-wise distillation in the paper "Structured Knowledge Distillation for Dense Prediction".
What about introducing Pair-wise & holistic distillations?

**Comment by VaticanCameos99** [comment]
Hi, 
Yes, I have limited the scope of this project to basic pixel-wise distillation only. 
You can find the other implementations on the author's repository for this paper: https://github.com/irfanICMLL/structure_knowledge_distillation

I hope this helps.
